### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by DippyFoxDerg** [imagitama/vrc3cvr#11]
Your converter is great for those just getting into CVR, and prime time as the EOC update came out to screw many innocent vrc users over. It is best you get to updating your converter to be more compatible with the latest CCK version when you are able to, [v3.3](https://developers.abinteractive.net/cck/setup/)

**Comment by imagitama** [comment]
I welcome any contributions people have to update it.

I will only update this if I play CVR again. The mods ban is annoying but CVR doesn't have anything like Udon and no Quest support so I won't be switching to it permanently.
