### ISSUE TITLE
Please mark as deprecated and broken until fixed

### ISSUE THREAD

**Issue by BerNo434** [imagitama/vrc3cvr#12]
With the recent surge of the CVR player base a bunch of people are attracted to this tool even though it is not functional in its current state. Can there please be a disclaimer added to mark this project as non functional until fixed.

**Comment by lmore377** [comment]
Not sure what you mean by non-functional. I just converted my avatar earlier today and the only thing that didn't convert over was the physbones.

**Comment by imagitama** [comment]
I added a message at the top of the README to explain that it *might* not work.
