### ISSUE TITLE
AnimatorTransitions ignored

### ISSUE THREAD

**Issue by NotAKidOnSteam** [imagitama/vrc3cvr#16]
AnimatorTransitions are currently ignored by the transition condition conversion, which causes issues with CGE and similar avatar setups.

**AnimatorStateTransitions** (Implemented)
AnimatorStateTransition always originate from an Animator State (or AnyState) and have timing parameters.

**AnimatorTransitions** (Needs Implementing)
AnimatorTransition always originate from a StateMachine or a StateMachine entry. They do not define timing parameters.

They both Inherit from **AnimatorTransitionBase**.

![image](https://user-images.githubusercontent.com/37721153/181867354-c5f56e26-9ee8-4ddd-8346-432574524d37.png)

**Comment by killfrenzy96** [comment]
I have a fix for this in my fork, I can submit a pull request if you like.

**Comment by imagitama** [comment]
Merged :)
