### ISSUE TITLE
Remove empty animator layers.

### ISSUE THREAD

**Issue by NotAKidOnSteam** [imagitama/vrc3cvr#17]
The script should remove empty animation layers from the final animator.
![image](https://user-images.githubusercontent.com/37721153/181870299-939d776b-04e9-4aa9-af6a-265993e2c45a.png)

**Comment by imagitama** [comment]
Why? Your original layers should not be empty.

**Comment by NotAKidOnSteam** [comment]
It's common to leave the first layer empty if you are using masks. The default FX and Gesture layers also leave the first layer empty.

**Comment by imagitama** [comment]
Merged :)
