### ISSUE TITLE
Fingers not moving on Wickerbeast

### ISSUE THREAD

**Issue by SectOLT** [imagitama/vrc3cvr#3]
I have attempted to use the tool on an avatar other than Canis or Rexouium, Wickerbeast by Jin A for instance.

The face expressions, tongue out and etc seems to work as intended, but somehow the hands do not react anymore, no bending, no pointing, fists closing, or anything like that, they're just straight

**Comment by imagitama** [comment]
I don't own that base model so can't test it. Can you please attach the animator controller(s) so I can take a look?

**Comment by SectOLT** [comment]
I have never really messed with Unity animations, what would the animator looks like ?

**Comment by imagitama** [comment]
Click "ChilloutVR Overrides" and then click the file in Unity:

![image](https://user-images.githubusercontent.com/1967342/112096877-09e3fd80-8bda-11eb-93c7-ab6e16ccf0b2.png)

Then at the top click "ChilloutVR_Gestures" and Unity should show you the animator controller that I need.

**Comment by SectOLT** [comment]
Sent over Discord

**Comment by imagitama** [comment]
Fixed in 0.0.9 by letting users keep the CVR hand animation layers
