### ISSUE TITLE
Converting avatar with INT always creates a Toggle

### ISSUE THREAD

**Issue by CailanVR** [imagitama/vrc3cvr#8]
I attempted to convert an avatar with an integer which goes from 1 to 80, and the converter still made it a toggle.

**Comment by imagitama** [comment]
Can you please go to the console tab and paste your logs?

**Comment by kingcailan** [comment]
The log is quite long, so I would rather simply share the logfile itself. The logs for the Chillout converter start at line 801. 

The animator layer dealing with the int in question starts at line 2415:
`Layer "Mute Phrases" with 106 states
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
VRC_Chillout_Converter:MergeVrcAnimatorIntoChilloutAnimator(AnimatorController) (at Assets\PeanutTools\VRC_Chillout_Converter\main.cs:704)
VRC_Chillout_Converter:MergeVrcAnimatorsIntoChilloutAnimator() (at Assets\PeanutTools\VRC_Chillout_Converter\main.cs:367)
VRC_Chillout_Converter:Convert() (at Assets\PeanutTools\VRC_Chillout_Converter\main.cs:141)
VRC_Chillout_Converter:OnGUI() (at Assets\PeanutTools\VRC_Chillout_Converter\main.cs:73)
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
UnityEditor.HostView:Invoke(String, Object)
UnityEditor.HostView:Invoke(String)
UnityEditor.HostView:InvokeOnGUI(Rect, Rect)
UnityEditor.DockArea:DrawView(Rect, Rect)
UnityEditor.DockArea:OldOnGUI()
UnityEngine.UIElements.IMGUIContainer:DoOnGUI(Event, Matrix4x4, Rect, Boolean, Rect, Action, Boolean)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Matrix4x4, Rect, Action, Boolean)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Action, Boolean)
UnityEngine.UIElements.IMGUIContainer:HandleIMGUIEvent(Event, Boolean)
UnityEngine.UIElements.IMGUIContainer:SendEventToIMGUI(EventBase, Boolean)
UnityEngine.UIElements.IMGUIContainer:HandleEvent(EventBase)
UnityEngine.UIElements.CallbackEventHandler:HandleEventAtTargetPhase(EventBase)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy:DispatchEvent(EventBase, IPanel)
UnityEngine.UIElements.EventDispatcher:ApplyDispatchingStrategies(EventBase, IPanel, Boolean)
UnityEngine.UIElements.EventDispatcher:ProcessEvent(EventBase, IPanel)
UnityEngine.UIElements.EventDispatcher:ProcessEventQueue()
UnityEngine.UIElements.EventDispatcher:OpenGate()
UnityEngine.UIElements.EventDispatcherGate:Dispose()
UnityEngine.UIElements.EventDispatcher:ProcessEvent(EventBase, IPanel)
UnityEngine.UIElements.EventDispatcher:Dispatch(EventBase, IPanel, DispatchMode)
UnityEngine.UIElements.BaseVisualElementPanel:SendEvent(EventBase, DispatchMode)
UnityEngine.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel)
UnityEngine.UIElements.UIElementsUtility:ProcessEvent(Int32, IntPtr)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
 `
 
 And the log entries for the parameter itself start at line 2918.

**Comment by kingcailan** [comment]
Sorry, my internet went out before I was able to upload the file separately.
[Editor.log](https://github.com/imagitama/vrc3cvr/files/6237449/Editor.log)

**Comment by imagitama** [comment]
```
Converting vrc parameters to chillout...
Getting all int options for param "DummyINT"...
Found 0 int options:
Param only has 1 option so we are making a toggle instead
Finished converting vrc params
```

I found a bunch of these and nothing about a param with 80 options. Will look into it

**Comment by imagitama** [comment]
I just looked at the code and it looks correct. All I can do is add extra logging and see if your logs change. Please try this new version and dump the logs again: https://github.com/imagitama/vrc3cvr/releases/tag/0.0.12

**Comment by kingcailan** [comment]
I did the conversion with the new update. For more info, this is the animator it's having problems with. Each of these states use an incremental value, and are all mutually exclusive:
![image](https://user-images.githubusercontent.com/18290108/114178534-7d3c7d80-9903-11eb-8d2d-60dc8d28d063.png)

And here is the log for this new update,
[Editor.log](https://github.com/imagitama/vrc3cvr/files/6285706/Editor.log)

**Comment by imagitama** [comment]
Thanks for the logs and screenshots but I don't have time to investigate this further as it seems pretty complicated. I would appreciate anyone's help with fixing this issue

**Comment by imagitama** [comment]
Yesterday I pushed a version that now keeps the parameter type (int, float, bool) instead of forcing it to be a float. This will probably fix your issue.
