### ISSUE TITLE
Null reference in `ConvertVrcParametersToChillout`

### ISSUE THREAD

**Issue by omgitsraven** [imagitama/vrc3cvr#9]
I'm trying the script for the first time, and it's giving me this error:

```
NullReferenceException: Object reference not set to an instance of an object
VRC_Chillout_Converter.ConvertVrcParametersToChillout () (at Assets/PeanutTools/VRC_Chillout_Converter/main.cs:288)
VRC_Chillout_Converter.Convert () (at Assets/PeanutTools/VRC_Chillout_Converter/main.cs:143)
VRC_Chillout_Converter.OnGUI () (at Assets/PeanutTools/VRC_Chillout_Converter/main.cs:73)
(etc...)
```

with line 288 being this:
```
for (int i = 0; i < vrcParams.parameters.Length; i++)
```

I've gotten around it by just wrapping the whole loop in a check for nulls:
```
if (vrcParams != null && vrcParams.parameters != null) {
```
(turns out it was the entire vrcParams being null, for the record)

After doing that, I was able to upload an avatar that seems to work right at first glance. Should I make a pull request?

**Comment by omgitsraven** [comment]
made the request just in case (with a slightly more concise change) : https://github.com/imagitama/vrc3cvr/pull/10

**Comment by imagitama** [comment]
Merged
